server:
  port:
    8080
spring:
  application:
    name: Test
  datasource:
    url: jdbc:mysql://localhost:3306/role_agent
    username: root
    password: xnylh
  ai:
    dashscope:
      api-key: {your-api-key}
      chat:
        options:
          model: qwen-plus
          enable-thinking: true

    mcp:
      client:
        request-timeout: 60000
        stdio:
          root-change-notification: true
          servers-configuration: classpath:mcp-servers.json

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            # 配置初始化脚本的位置
            schema: classpath:org/springframework/ai/chat/memory/repository/jdbc/schema-mariadb.sql
            platform: mariadb

    datasource:
      url: jdbc:mysql://127.0.0.1:3306/role_agent?useUnicode=true&characterEncoding=utf8&autoReconnectForPools=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: xnylh
      driver-class-name: com.mysql.cj.jdbc.Driver
    retry:
      max-attempts: 3

logging:
  level:
    root: INFO
    org:
      springframework:
        ai:
          chat:
            client:
              advisor:
                SimpleLoggerAdvisor: DEBUG

search-api:
  key: {your-search-api-key}