server:
  port:
    8080
spring:
  application:
    name: Test
  datasource:
    url: jdbc:mysql://localhost:3306/role_agent
    username: root
    password: xnylh
  ai:
    dashscope:
      api-key: {api-key}
      chat:
        options:
          model: qwen-turbo


logging:
  level:
    root: INFO
    org:
      springframework:
        ai:
          chat:
            client:
              advisor:
                SimpleLoggerAdvisor: DEBUG



